[project]
name = "flaskapifprmat"
version = "0.1.0"
description = "Flask+FlaskOpenAPI3を使ってみよう"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "flask-openapi3[swagger]>=4.1.0",
]
